# Generated by Django 4.1.4 on 2023-01-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_rename_post_musicinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicinfo',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts/'),
        ),
    ]
