# Generated by Django 4.1.4 on 2023-01-26 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_image_alter_comment_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
