# Generated by Django 4.1.5 on 2023-01-31 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vip',
            name='update_at',
        ),
    ]
